// engine/runtime/createApp.ts
import fs from "fs/promises";
import path from "path";
import { Intent } from "../intent/classify";
import { writeWorkspace } from "../fs/writeWorkspace";
import { prisma } from "../store/prisma";

export async function instantiateProject(intent: Intent) {
  // Create DB record
  const project = await prisma.app.create({
    data: {
      name: intent.name,
      description: intent.description ?? "",
      status: "CREATED",
    },
  });

  // Create folder
  const dir = path.join(process.cwd(), "workspace", project.id);
  await fs.mkdir(dir, { recursive: true });

  // Default files
  const index = `
import React from 'react';
export default function App() {
  return (
    <main>
      <h1>${intent.name}</h1>
      <p>${intent.description ?? "Generated by Ideatorium"}</p>
      <ul>
        ${intent.features.map((f) => `<li>${f}</li>`).join("\n")}
      </ul>
    </main>
  );
}
`;
  await writeWorkspace(dir, "page.tsx", index);

  return { id: project.id, name: project.name };
}