// engine/blueprints/web-app.ts
import { Intent } from "../intent/classify";

export function webAppBlueprint(intent: Intent) {
  return {
    files: {
      "page.tsx": `
import React from 'react';
export default function App() {
  return (
    <main style={{ fontFamily: 'sans-serif' }}>
      <h1>${intent.name}</h1>
      <p>${intent.description ?? "Generated by Ideatorium"}</p>
    </main>
  );
}`,
      "package.json": `
{
  "name": "${intent.name.toLowerCase().replace(/\s+/g, "-")}",
  "version": "1.0.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "14.x",
    "react": "18.x",
    "react-dom": "18.x"
  }
}`,
    },
  };
}